sudo: required

services: docker

before_install:
  - docker-compose up --build -d
  # Login heroku docker registory
  # - docker login -u "$HEROKU_USERNAME" -p "HEROKU_API_KEY" registry.heroku.com
  # _ api login
  - docker login -u "_" -p "$HEROKU_API_KEY" registry.heroku.com

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create 
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test

deploy:
  provider: script
  script:
    docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile.prod .;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku run --app $HEROKU_APP_NAME rails db:migrate;
  on:
    branch: master # Deploy only when the master branch is merged
